### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by GISplunk** [jorritfolmer/TA-ct-log#1]
We're having the following errors occur in our Splunk instance for the TA-ct-log.  Any assistance in resolving these would be greatly appreciated.

message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" input_module.collect_events(self, ew) 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" obj.process_log() 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" self.collect_events(ew) 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" File "/opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py", line 64, in collect_events 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" File "/opt/splunk/etc/apps/TA-ct-log/bin/input_module_ct_log.py", line 26, in collect_events 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" File "/opt/splunk/etc/apps/TA-ct-log/bin/ta_ct_log/modinput_wrapper/base_modinput.py", line 127, in stream_events
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" Traceback (most recent call last): 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" raise ValueError("No JSON object could be decoded")
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" return _default_decoder.decode(s) 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" sth = json.loads(r.text)
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" tree_size = self.get_tree_size()
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" File "/opt/splunk/etc/apps/TA-ct-log/bin/ctl/ctl2splunk.py", line 169, in get_tree_size
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" File "/opt/splunk/etc/apps/TA-ct-log/bin/ctl/ctl2splunk.py", line 201, in process_log 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" File "/opt/splunk/lib/python2.7/json/__init__.py", line 339, in loads 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" File "/opt/splunk/lib/python2.7/json/decoder.py", line 364, in decode 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" File "/opt/splunk/lib/python2.7/json/decoder.py", line 382, in raw_decode 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" ERRORNo JSON object could be decoded 
message from "python /opt/splunk/etc/apps/TA-ct-log/bin/ct_log.py" ValueError: No JSON object could be decoded

**Comment by jorritfolmer** [comment]
Can you share which ct log you’re getting this with, so I can try to reproduce?

**Comment by GISplunk** [comment]
It appears to be ct.googleapis.com type logs.

**Comment by jorritfolmer** [comment]
Ok thanks I’ll try to find some time this weekend

**Comment by jorritfolmer** [comment]
It appears the request to get information about the sth tree is successful but returns nothing. This looks like a glitch in ct.googleapis.com as I haven't been able to reproduce it.

I think it should continue its next iteration after 300 seconds. Is that the case?
