### ISSUE TITLE
Feature req: add proxy support

### ISSUE THREAD

**Issue by jorritfolmer** [jorritfolmer/TA-ct-log#2]
Following https://answers.splunk.com/answers/730688/how-to-configure-ct-logs-with-proxy.html

**Comment by jorritfolmer** [comment]
Implemented in most recent commit to master.
The configure screen now has an extra tab for proxy.
Any feedback?

**Comment by owltechtn** [comment]
I have to add both addons  {old and new} inorder to make the new one worked.
If I remove the old one, new one is giving page load error.

Also, when trying to save the proxy details, the page is hanging at saving mode but unable to finish the job.

**Comment by owltechtn** [comment]
The Certificate transparency addon started working now after updating the proxy details locally in the server.

I have removed the new version of addon from the environment.

**Comment by jorritfolmer** [comment]
With the most recent commit I fixed the errors you've been getting. 
It now works for me in my testlab with a Squid proxy.
I assume it will now also work properly for you, can you verify?
